version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nextjs-app:
    container_name: nextjs-app

    build:
      context: .
      dockerfile: Dockerfile

    env_file: ./.env
    ports:
      - 3000:3000

    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy
